### PR TITLE
Update DExtra_Hosts.txt

### PR DESCRIPTION
**Pull request by vk4tux**
Update ?

### CODE REVIEW

**Comment by EA3HKB** [comment]
Hello!!
Is possible add new working reflector??

XRF714    ea3hkb.com

Thanks.
Sergi. EA3HKB.

**Comment by vk4tux** [comment]
On 28/08/15 10:23, EA3HKB wrote:
> XRF714 ea3hkb.com

Thankyou

Adrian ... vk4tux

**Comment by vk4tux** [comment]
@Sergi. EA3HKB

Dashboard page for XRF714 please?




XRF000	000.xreflector.org
XRF001	75.76.90.90
XRF002	91.201.57.233
XRF003	95.110.157.83
XRF004	96.36.58.9
XRF005	216.16.240.236
XRF006	80.62.20.151
XRF007	84.232.6.94
XRF008	95.110.231.219
XRF009	141.22.15.29
XRF010	87.106.48.7
XRF011	87.106.3.249
XRF012	xreflector12.dstarsandiego.com
XRF013	xrf013.vkradio.com
XRF015	xrf015.theapplecore.me
XRF017	87.253.159.114
XRF018	199.167.129.166
XRF019	66.30.81.236
XRF020	67.210.212.144
XRF021	74.204.50.67
XRF022	xrf022.tms-it.net
XRF023	141.75.245.225
XRF024	xrf024.dstar.at
XRF025	63.133.189.2
XRF026	139.13.100.34
XRF027	194.116.29.78
XRF028	193.190.240.228
XRF030	xrf030.oe3xht.at
XRF031	83.241.141.245
XRF033	46.226.178.81
XRF036	xrf036.ddns.net
XRF038	66.6.171.228
XRF041	167.88.37.80
XRF044	82.1.185.173
XRF045	045.xreflector.org
XRF048	xrf048.n5uxt.net
XRF050	050.xreflector.org
XRF055	95.110.229.195
XRF063	162.248.141.148
XRF067	xrf067.f5kav.org
XRF069	37.187.176.70
XRF070	182.161.156.13
XRF073	147.102.7.34
XRF077	xrf077.duckdns.org
XRF078	217.112.102.132
XRF084	xrf084.fabbroni.eu
XRF088	xrf088.pa4tw.nl
XRF090	46.37.185.184
XRF099	76.71.89.114
XRF100	88.46.211.5
XRF111	5.196.3.184
XRF112	92.222.47.175
XRF117	xrf117.dyndns.org
XRF119	149.154.158.170
XRF123	213.126.90.100
XRF133	xrf133.gb7de.co.uk
XRF168	xrf168.duckdns.org
XRF185	xrf185.dyndns.org
XRF200	xrf200.theapplecore.me
XRF210	210.xreflector.org
XRF228	xrf228.duckdns.org
XRF232	xrf232.tms-it.net
XRF250	xrf250.dstar.su
XRF255	xrf255.reflector.up4dar.de
XRF262	xrf262.reflector.up4dar.de
XRF295	104.167.96.2
XRF307	104.167.106.95
XRF310	server1.xrefl.net
XRF333	xrf333.f1smf.com
XRF353	94.173.206.53
XRF400	xrf400.no-ip.org
XRF420	kc9qen.com
XRF444	70.125.157.44
XRF450	450.xreflector.org
XRF500	xrf500.org
XRF555	54.191.67.121
XRF559	98.239.113.175
XRF580	67.20.31.79
XRF600	88.96.217.121
XRF603	74.104.179.159
XRF666	vpngrf.webandcloud.net #VPN
XRF669	xrf669.no-ip.org
XRF707	xrf707.openquad.net
XRF714	ea3hkb.com
XRF720	204.45.107.21
XRF727	108.33.72.83
XRF740	imagewell.duckdns.org
XRF748	104.167.109.27
XRF757	xrf757.openquad.net
XRF773	xrf773.iz0rin.it
XRF777	62.167.15.53
XRF780	96.53.97.22
XRF851	xrf851.rsdt.de
XRF858	198.57.255.30
XRF870	103.18.207.114
XRF888	5.135.147.180
XRF901	xrf901.dyndns.org
XRF902	xrf902.dyndns.org
XRF905	199.212.121.20
XRF906	xrf906.radioclubveleta.es
XRF911	xrf911.ns0.it
XRF929	xrf929.ddns.net
XRF978	74.104.179.159
XRF987	xrf987.metro-uhf.org
XRF988	46.105.27.191
XRF988	46.105.27.191
XRF989	104.167.119.5
XRFWDX	xrfwdx.ham-radio-op.net

**Comment by EA3HKB** [comment]
The dashboard is under construction in this moment

**Comment by vk4tux** [comment]
Thankyou,

Please email

vk4tux@bigpond.com

with url, or do you know the url already? it will be added to

http://vk4tux.duckdns.org/lookup.html

73

Adrian ... vk4tux

**Comment by EA3HKB** [comment]
Hello
The URL reserved is 

xrf714.ea3hkb.com

73's

**Comment by EA3HKB** [comment]
Hi Adrian.

Use xrf714.ea3hkb.com for the dextra reflector too, if possible

Thanks.

Sergi, EA3HKB

**Comment by vk4tux** [comment]
OK Thankyou

**Comment by vk4tux** [comment]
On 28/08/15 22:53, EA3HKB wrote:
>
> Hi Adrian.
>
> Use xrf714.ea3hkb.com for the dextra reflector too, if possible
>
> Thanks.
>
> Sergi, EA3HKB
>
>
XRF000	000.xreflector.org
XRF001	75.76.90.90
XRF002	91.201.57.233
XRF003	95.110.157.83
XRF004	96.36.58.9
XRF005	216.16.240.236
XRF006	80.62.20.151
XRF007	84.232.6.94
XRF008	95.110.231.219
XRF009	141.22.15.29
XRF010	87.106.48.7
XRF011	87.106.3.249
XRF012	xreflector12.dstarsandiego.com
XRF013	xrf013.vkradio.com
XRF015	xrf015.theapplecore.me
XRF017	87.253.159.114
XRF018	199.167.129.166
XRF019	66.30.81.236
XRF020	67.210.212.144
XRF021	74.204.50.67
XRF022	xrf022.tms-it.net
XRF023	141.75.245.225
XRF024	xrf024.dstar.at
XRF025	63.133.189.2
XRF026	139.13.100.34
XRF027	194.116.29.78
XRF028	193.190.240.228
XRF030	xrf030.oe3xht.at
XRF031	83.241.141.245
XRF033	46.226.178.81
XRF036	xrf036.ddns.net
XRF038	66.6.171.228
XRF041	167.88.37.80
XRF044	82.1.185.173
XRF045	045.xreflector.org
XRF048	xrf048.n5uxt.net
XRF050	050.xreflector.org
XRF055	95.110.229.195
XRF063	162.248.141.148
XRF067	xrf067.f5kav.org
XRF069	37.187.176.70
XRF070	182.161.156.13
XRF073	147.102.7.34
XRF077	xrf077.duckdns.org
XRF078	217.112.102.132
XRF084	xrf084.fabbroni.eu
XRF088	xrf088.pa4tw.nl
XRF090	46.37.185.184
XRF099	76.71.89.114
XRF100	88.46.211.5
XRF111	5.196.3.184
XRF112	92.222.47.175
XRF117	xrf117.dyndns.org
XRF119	149.154.158.170
XRF123	213.126.90.100
XRF133	xrf133.gb7de.co.uk
XRF168	xrf168.duckdns.org
XRF185	xrf185.dyndns.org
XRF200	xrf200.theapplecore.me
XRF210	210.xreflector.org
XRF228	xrf228.duckdns.org
XRF232	xrf232.tms-it.net
XRF250	xrf250.dstar.su
XRF255	xrf255.reflector.up4dar.de
XRF262	xrf262.reflector.up4dar.de
XRF295	104.167.96.2
XRF307	104.167.106.95
XRF310	server1.xrefl.net
XRF333	xrf333.f1smf.com
XRF353	94.173.206.53
XRF400	xrf400.no-ip.org
XRF420	kc9qen.com
XRF444	70.125.157.44
XRF450	450.xreflector.org
XRF500	xrf500.org
XRF555	54.191.67.121
XRF559	98.239.113.175
XRF580	67.20.31.79
XRF600	88.96.217.121
XRF603	74.104.179.159
XRF666	vpngrf.webandcloud.net #VPN
XRF669	xrf669.no-ip.org
XRF707	xrf707.openquad.net
XRF714	xrf714.ea3hkb.com
XRF720	204.45.107.21
XRF727	108.33.72.83
XRF740	imagewell.duckdns.org
XRF748	104.167.109.27
XRF757	xrf757.openquad.net
XRF773	xrf773.iz0rin.it
XRF777	62.167.15.53
XRF780	96.53.97.22
XRF851	xrf851.rsdt.de
XRF858	198.57.255.30
XRF870	103.18.207.114
XRF888	5.135.147.180
XRF901	xrf901.dyndns.org
XRF902	xrf902.dyndns.org
XRF905	199.212.121.20
XRF906	xrf906.radioclubveleta.es
XRF911	xrf911.ns0.it
XRF929	xrf929.ddns.net
XRF978	74.104.179.159
XRF987	xrf987.metro-uhf.org
XRF988	46.105.27.191
XRF988	46.105.27.191
XRF989	104.167.119.5
XRFWDX	xrfwdx.ham-radio-op.net

**Comment by EA3HKB** [comment]
Ok!!!!!
73's

**Comment by remcovz** [comment]
I see my reflector (XRF088) is also in the list, but not yet in the diff. How or when will this be merged into the final release?
73, Remco/PA4TW

**Comment by vk4tux** [comment]
On 10/09/15 21:57, Remco van Zuijlen wrote:
>
> I see my reflector (XRF088) is also in the list, but not yet in the 
> diff. How or when will this be merged into the final release?
> 73, Remco/PA4TW
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dl5di/OpenDV/pull/4#issuecomment-139213632>.
>
XRF000	000.xreflector.org
XRF001	75.76.90.90
XRF002	91.201.57.233
XRF003	95.110.157.83
XRF004	96.36.58.9
XRF005	216.16.240.236
XRF006	80.62.20.151
XRF007	84.232.6.94
XRF008	95.110.231.219
XRF009	141.22.15.29
XRF010	87.106.48.7
XRF011	87.106.3.249
XRF012	xreflector12.dstarsandiego.com
XRF013	xrf013.vkradio.com
XRF015	xrf015.theapplecore.me
XRF017	87.253.159.114
XRF018	199.167.129.166
XRF019	66.30.81.236
XRF020	67.210.212.144
XRF021	74.204.50.67
XRF022	xrf022.tms-it.net
XRF023	141.75.245.225
XRF024	xrf024.dstar.at
XRF025	63.133.189.2
XRF026	139.13.100.34
XRF027	194.116.29.78
XRF028	193.190.240.228
XRF030	xrf030.oe3xht.at
XRF031	83.241.141.245
XRF033	46.226.178.81
XRF036	xrf036.ddns.net
XRF038	66.6.171.228
XRF040	xrf040.dyndns.org
XRF041	167.88.37.80
XRF044	82.1.185.173
XRF045	045.xreflector.org
XRF048	xrf048.n5uxt.net
XRF050	050.xreflector.org
XRF055	95.110.229.195
XRF063	162.248.141.148
XRF067	xrf067.f5kav.org
XRF069	37.187.176.70
XRF070	182.161.156.13
XRF073	147.102.7.34
XRF077	xrf077.duckdns.org
XRF078	217.112.102.132
XRF084	xrf084.fabbroni.eu
XRF088	xrf088.pa4tw.nl
XRF090	46.37.185.184
XRF099	76.71.89.114
XRF100	88.46.211.5
XRF111	5.196.3.184
XRF112	92.222.47.175
XRF117	xrf117.dyndns.org
XRF119	149.154.158.170
XRF123	213.126.90.100
XRF133	xrf133.gb7de.co.uk
XRF168	xrf168.duckdns.org
XRF185	xrf185.dyndns.org
XRF200	xrf200.theapplecore.me
XRF210	210.xreflector.org
XRF228	xrf228.duckdns.org
XRF232	xrf232.tms-it.net
XRF250	xrf250.dstar.su
XRF255	xrf255.reflector.up4dar.de
XRF262	xrf262.reflector.up4dar.de
XRF295	104.167.96.2
XRF307	104.167.106.95
XRF310	server1.xrefl.net
XRF333	xrf333.f1smf.com
XRF353	94.173.206.53
XRF400	xrf400.no-ip.org
XRF420	kc9qen.com
XRF444	70.125.157.44
XRF450	450.xreflector.org
XRF500	xrf500.org
XRF555	54.191.67.121
XRF559	98.239.113.175
XRF580	67.20.31.79
XRF600	88.96.217.121
XRF603	74.104.179.159
XRF666	vpngrf.webandcloud.net #VPN
XRF669	xrf669.no-ip.org
XRF707	xrf707.openquad.net
XRF714	xrf714.ea3hkb.com
XRF720	204.45.107.21
XRF727	108.33.72.83
XRF740	imagewell.duckdns.org
XRF748	104.167.109.27
XRF757	xrf757.openquad.net
XRF773	xrf773.iz0rin.it
XRF777	62.167.15.53
XRF780	96.53.97.22
XRF851	xrf851.rsdt.de
XRF858	198.57.255.30
XRF870	103.18.207.114
XRF888	5.135.147.180
XRF901	xrf901.dyndns.org
XRF902	xrf902.dyndns.org
XRF905	199.212.121.20
XRF906	xrf906.radioclubveleta.es
XRF911	xrf911.ns0.it
XRF929	xrf929.ddns.net
XRF978	74.104.179.159
XRF987	xrf987.metro-uhf.org
XRF988	46.105.27.191
XRF989	104.167.119.5
XRFWDX	xrfwdx.ham-radio-op.net

**Comment by remcovz** [comment]
Thanks, I saw the reflector was already added in the merged data (not from this pull request) on:

https://github.com/dl5di/OpenDV/blob/master/ircDDBGateway/Data/DExtra_Hosts.txt

**Comment by vk4tux** [comment]
On 10/09/15 22:06, Remco van Zuijlen wrote:
>
> Thanks, I saw the reflector was already added in the merged data (not 
> from this pull request) on:
>
> https://github.com/dl5di/OpenDV/blob/master/ircDDBGateway/Data/DExtra_Hosts.txt
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dl5di/OpenDV/pull/4#issuecomment-139215369>.
>
Ok That is the vk4tux host file extract, you are welcome to add it.

Adrian ... vk4tux

**Pull request closed without merging**
