### PR TITLE
Move DStarRepeater to GNU Autoconf

### PR DESCRIPTION
**Pull request by mcdermj**
Autoconf/automake are the standard make utilities on Linux.  Using them allows users to do the standard configure/make workflow which makes things easier for building.  It also opens up some opportunities for easier conditional compilation.  This patch moves DStarRepeater to use autoconf instead of a collection of Makefiles on Linux.  As Windows does not use the Makefile system, this should have no effect on that port.

The system has a couple of different features to be noted:
*  libasound, wxWidgets and libUSB are all automatically detected and the configure script will fail if they can't be found.
*  dstarrepeaterd is compiled with only the base wxWidgets library so that it doesn't bring in any of the X-windows system.  This should allow small systems to use it without having to install any of the graphical packages.  If you inspect the result with ldd, there are only a handful of shared libraries required.
*  The compilation of dstarrepeater and dstarrepeaterconf can be suppressed by passing configure the --without-gui flag
*  The GPIOController can be compiled up by passing the --with-gpio flag to configure.  It will automatically verify wiringPi is installed.

The patch has been tested on Ubuntu x86_64 and Raspbian on the Raspberry Pi 2.

There's still more work to be done along these lines.  It should be relatively easy to do a couple of things:
*  Compile without LibUSB by pulling out the GMSKController, URIController and K8055Controller in the build.  This can be flagged with a --without-usb flag
*  Compile without sound support, and select the proper sound system (ALSA/Portaudio).  This should again allow smaller binaries, and the sound detection should make things easier for MacOS X.
*  Move ircDDBGateway and the rest of the programs to autoconf as well.

### CODE REVIEW

**Comment by sq7lrx** [comment]
Great idea

**Comment by F4FXL** [comment]
This is cool indeed ! Any plans to migrate other components ?

**Comment by SpudGunMan** [comment]
There has been no further work on this and it hasnt been added to other projects making this super confusing. I recommend that we revert this pull until such time someone finishes the work

**Comment by F4FXL** [comment]
Apparently work is in progress https://github.com/dl5di/OpenDV/pull/73

**Pull request merged**
