### PR TITLE
APRSTransmitd now supporting custom filters

### PR DESCRIPTION
**Pull request by F4FXL**
Custom filters as per http://www.aprs-is.net/javaprsfilter.aspx are now supported
This also fixes aprstransmitd not starting as a service

### CODE REVIEW

**Comment by F4FXL** [comment]
Hi
Ok I'll changebit back asap.




-------- Message d'origine --------
De : Jeremy McDermond <notifications@github.com> 
Date : 25/09/2016  08:57  (GMT+01:00) 
À : dl5di/OpenDV <OpenDV@noreply.github.com> 
Cc : Geoffrey Merck <f4fxl@planetemax.com>, Author <author@noreply.github.com> 
Objet : Re: [dl5di/OpenDV] APRSTransmitd now supporting custom filters (#107) 

@mcdermj commented on this pull request.



In ircDDBGateway/debian/aprstransmitd.aprstransmitd@.service:
> @@ -6,7 +6,7 @@ After=ircddbgatewayd.service
 [Service]
 User=opendv
 EnvironmentFile=/etc/opendv/aprstransmitd.conf
-ExecStart=/usr/sbin/aprstransmitd $i -host $APRS_SERVER -port $APRS_PORT -radius $RADIUS
+ExecStart=/usr/sbin/aprstransmitd $REPEATER -host $APRS_SERVER -port $APRS_PORT -filter ${FILTER}

This change is incorrect and misunderstands the usage of the unit file.  It's set up to allow multiple instances and should be started as:

systemctl start aprstransmitd@ABCDE__B

What should happen is that the EnvironmentFile should be templated to allow for more config files in /etc/opendv for each daemon instance.  So, probably should be:

EnvironmentFile=/etc/opendv/aprstransmitd-$i.conf

and the corresponding config file changes to:

/etc/opendv/aprstransmitd-ABCDE__B.conf

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dl5di/OpenDV","title":"dl5di/OpenDV","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dl5di/OpenDV"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mcdermj commented on #107"}],"action":{"name":"View Pull Request","url":"https://github.com/dl5di/OpenDV/pull/107#pullrequestreview-1447294"}}}

**Comment by mcdermj** [comment]
I’ll take a look at this and push a fix for the config file issue.  I might be able to get you something on this later this afternoon (Pacific Time).

--
Jeremy McDermond
nh6z@nh6z.net

**Comment by F4FXL** [comment]
I just arrived home, previous reply was sent from my phone. I'll update the PR in the next minutes.

**Comment by F4FXL** [comment]
I was unaware of the syntax of the config file. Systemd is quite new to me.

**Comment by F4FXL** [comment]
It is working, yet I have some issues templating the config file

**Comment by mcdermj** [comment]
Yeah, I had thought that it was % instead of $ after I thought about it a bit.  That's what I get for shooting from the hip without reading the docs again.

This looks good to me.  The _ matches `dstarrepeaterd` so it should be fairly straight forward for people.

**Pull request merged**
