### PR TITLE
Add URI device as a controller option in DStarRepeater

### PR DESCRIPTION
**Pull request by N5QM**
These changes add the ability to use a DMK Engineering URI device as a controller to trigger the PTT on the attached radio for the DStarRepeater application.

### CODE REVIEW

**Comment by SpudGunMan** [comment]
could you also implement this on the analog repeater code, since you have it all handy

**Comment by N5QM** [comment]
Sure, I would rather do it as two separate requests though.

I have tested this in simplex mode this evening and it works like a champ!

**Comment by SpudGunMan** [comment]
awesome. for sure.. just thought since you have the hardware and the recent code handy might as well fix this everywhere.

**Comment by F4FXL** [comment]
Hi,

It seems you did not include your work into the VS2008 project.
BTW where did you get HID.h ? I downloaded the latest Windows Driver Kit from MS and it seems HID.h has been superseeded by hidsid.h ...

**Comment by SpudGunMan** [comment]
a lot of us dont use VS to code with, could you retroactively add it to your project files to maintain those that do?

**Comment by N5QM** [comment]
Hello,

I don't use VS2008, I just used a text editor.  I will need some assistance from someone familiar with VS to get that done.

HID.h was already included in the repository, it wasn't added by me.  :-)

**Comment by F4FXL** [comment]
Hi,

I must be stupid but I was unable to locate HID.h it in the repository. How did you compile it under windows ?
Currently, I am in the process to upgrade the DStarRepeater to VS2015. Maybe I'll be able to push something this evening. I will try to include your work.

**Comment by N5QM** [comment]
I did not compile it under Windows.  The URI has issues under windows by which the volume adjustments get changed based on input to the GPIO pins, so from browsing through the list archives people are not using it on windows.

**Comment by F4FXL** [comment]
Ok.... I wish I could have read your comment before, I already added your work in my upgrade :)

**Comment by F4FXL** [comment]
https://github.com/dl5di/OpenDV/pull/53

**Comment by SpudGunMan** [comment]
Well it's not horrible to have it - to compile is still ok we might fix the problem noted some day - it won't hurt the compile since the hang up seems to be the HiD issue for this and other items correct?

**Comment by N5QM** [comment]
I agree, as long as other functionality isn't impacted by including it, I don't see the harm.

**Comment by F4FXL** [comment]
It's included in VS2015, I do not have VS2008 to include it there ....

**Pull request merged**
