### PR TITLE
Correct IP

### PR DESCRIPTION
**Pull request by F4FXL**
Hi,

Added a simple APRS Parser to filter icom id51/5100 unsupported packets
73
Geoffrey F4FXL  / KC3FRA

### CODE REVIEW

**Comment by F4FXL** [comment]
Nevermind, still a failed commit

**Comment by F4FXL** [comment]
Ok now it can be merged !

**Comment by g4klx** [comment]
Hi Geoffrey
Thanks for the fixes, however some points to remember:
1. Not all compilers are C++11 capable, keep the code simple.
2. A reference cannot be checked against NULL.
3. Enumerations and such like should have prefixes so they don't clash with other objects. Unknown was also declared in the Windows headers. It is such a general label that it is dangerous anyway.
4. There is no way to run this as a non daemon. Windows still needs support. Please look at the other programs and follow their pattern, allow APRS Transmit to be run on other platforms.
Your changes, plus mine have been merged.
Jonathan  G4KLX

**Comment by g4klx** [comment]
Also...... please don't check in binaries......

**Comment by F4FXL** [comment]
Hi Jonathan,

I will amend the code ASAP. I'm fixing some stuff in the new APRSParser. The Icom radios are quite stupid in regard of what they can decode... I'm adding some basic conversion.
I've been away from C++ since over a decade, I have been mainly into C# .Net mono world  hence the delegating constructors and NULL references checks.
Shall I amend the code to avoid delegating constructors ?

Sorry for commit binaries... Did not pay attention.

I oriented the code of aprstansmitd on the one of ircddbgatewayd. Actually most of the code of the main function is borrowed from there. Which part did I miss ?

**Comment by g4klx** [comment]
Hi Geoffrey
I've done most of the changes needed for compilation under Windows so a git pull should be interesting :-)
Please avoid delegation constructors, that was the only major C++ change I found. I did try and use the new SlowDataEncoder on the D-Star and Dummy repeaters and failed, you missed out some of the code that I had in the original version, like slow data message addition and the (unused) code squelch code also. If you replace my versions, please implement all that I had, as well as adding new parts.
With my code I have something like APRSTransmit.{cpp,h} for non daemon execution and APRSTransmitD.{cpp,h} for the daemon version. On Linux both are built, while on Windows only the non daemon version is.
I hope that makes sense.
Jonathan  G4KLX

**Comment by F4FXL** [comment]
Hi Jonathan,

I am not sure to understand what you meant with "*I did try and use the new SlowDataEncoder on the D-Star and Dummy repeaters and failed, you missed out some of the code that I had in the original version, like slow data message addition and the (unused) code squelch code also*" can you expand ?

- I started working on the SlowDataEncoder in ircddbGateway which was the pretty much the same as in DstarRepeater. However, the one in DStarRepeater does not ensure the string is 20 char long. The original (and the current) SlowDataEncoder in ircDDBGateway do that. Considering this, I do not think using it in DStarRepeater should make an issue. It might be wrong and missed something.

- I did not look at the SlowDataEncoder in dummy repeater. My mistake ...

73
Geoffrey F4FXL / KC3FRA

**Pull request merged**
