### PR TITLE
Bugfix : ircDDBGateway fails to report to ircddb

### PR DESCRIPTION
**Pull request by F4FXL**
Here the bugfix of the issue discussed here https://groups.yahoo.com/neo/groups/ircddb/conversations/topics/2216
and here https://groups.yahoo.com/neo/groups/KLX-developers/conversations/messages/23

### CODE REVIEW

**Comment by delqn** [comment]
Thank you for fixing this!

**Comment by F4FXL** [comment]
Wow ! Lightning fast !  
  
Merged #41.�

**Comment by F4FXL** [comment]
No problem ! :)  
  
Thank you for fixing this!�

**Comment by SpudGunMan** [comment]
everything works here as expected with ircDDB reporting

**Comment by F4FXL** [comment]
You mean with this bugfix ?
Without this bugfix openquad was working but the "official" ircDDB was not working.

**Comment by SpudGunMan** [comment]
With your fix sorry yes

**Pull request merged**
