### PR TITLE
Update DPlus_Hosts.txt

### PR DESCRIPTION
**Pull request by vk4tux**
Update ? host addresses only cover a minority of reflectors.
IP list is more functional and can be updated easily.

### CODE REVIEW

**Comment by n8ohu** [comment]
Neither Jonathan or Hans have the time to do the updates needed, since it would require releasing at minimum a new file with the updated IP addresses; I believe this is why Jonathan made the most recent change to use the fully qualified domain name instead.

**Comment by vk4tux** [comment]
On 26/05/15 12:12, Matthew wrote:
>
> Neither Jonathan or Hans have the time to do the updates needed, since 
> it would require releasing at minimum a new file with the updated IP 
> addresses; I believe this is why Jonathan made the most recent change 
> to use the fully qualified domain name instead.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dl5di/OpenDV/pull/5#issuecomment-105359802>.
>
Well, I put the hostname list version on the group for a certain user to 
try on request, however only 20% of the name list works.
I spent a lot of time testing it. There will be many complaints if you 
release that.

Why not just let me update them ?

**Comment by n8ohu** [comment]
ircDDBGateway can read custom *_Hosts.txt files placed in either the /root directory or /home/opendv user directory and use them instead of the defaults; I've been running my personal gateway this way since the capability was added, because I also run an XReflector on the same IP address and need to be able to access it with a different IP than outside users would. There is nothing wrong with wanting to keep the lists updated, it's just that an alternate mechanism exists to do what you want.

**Comment by johnhays** [comment]
One could create a separate repository and then people could use apt-get,
yum, etc. to get the custom lists.

On Tue, May 26, 2015 at 3:08 PM, Matthew <notifications@github.com> wrote:

> ircDDBGateway can read custom *_Hosts.txt files placed in either the /root
> directory or /home/opendv user directory and use them instead of the
> defaults; I've been running my personal gateway this way since the
> capability was added, because I also run an XReflector on the same IP
> address and need to be able to access it with a different IP than outside
> users would. There is nothing wrong with wanting to keep the lists updated,
> it's just that an alternate mechanism exists to do what you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dl5di/OpenDV/pull/5#issuecomment-105681887>.
>



-- 

------------------------------
John D. Hays
K7VE

PO Box 1223, Edmonds, WA 98020-1223
<http://k7ve.org/blog>  <http://twitter.com/#!/john_hays>
<http://www.facebook.com/john.d.hays>

**Pull request closed without merging**
