### PR TITLE
Still bugfix the stripped slodata when in gateway mode

### PR DESCRIPTION
**Pull request by F4FXL**
Hi Hans and Jonathan,

I Know this is not official repo, but still I invested some time to add some logic that will only overwrite the header part of the slow data.

I added some logic to support this, it seems to work ....

73
Geoffrey F4FXL

### CODE REVIEW

**Comment by g4klx** [comment]
The fix isn't correct. It makes the assumption that only odd numbered frames have slow data that is the header. I am not sure what the rule is for slow data, especially when it includes GPS, GPS-A, etc. Therefore it may be better to change the slow data every five blocks throughout the transmission which should provide enough unchanged slow data to allow for the original text to appear.
Once the correct header data has been received by the repeater then subsequent headers are not considered by it.
Jonathan  G4KLX

**Comment by g4klx** [comment]
Ooops, you're code is right, I was wrong!
I've committed your changed to the OpenDV repository.
I can see a potential bug with it though, it would be better if the code could be changed so that the whole slow data for a block is changed if the first type of the block is of type header, as later ones may be corrupt but can be replaced safely.
Jonathan  G4KLX

**Comment by F4FXL** [comment]
Hi Jonathan,

Maybe my comment in the code has mis-leaded you it was meant to say that only odd frames have the "header byte" that says which kind of slow data we currently have. This way of doing also handles interleaving of slow data.
Not sure to fully understand what you meant with this statement : "it would be better if the code could be changed so that the whole slow data for a block is changed if the first type of the block is of type header, as later ones may be corrupt but can be replaced safely."
Do you mean we could throw away all the slow data if the first one is a header ?

73
Geoffrey F4FXL

**Comment by g4klx** [comment]
Hi Geoffrey
I probably need to explain myself better. You were right about the odd number frames containing the slow data type. I was thinking of something else when I sent my first e-mail.
My other comment is more complex, but since you have been working with slow data, I hope you can understand the potential problem. As you know there is a sync pattern every 21 frames in D-Star, between these syncs are 20 frames of slow data (with 10 slow data type bytes). We will call this a block of slow data.
The slow data header exists completely in one block of slow data, and never overlaps into a second block, and it always starts in the first frame after the sync.
There is no FEC on slow data headers, or the slow data type meaning that it may be corrupted. So in order to replace the slow data header correctly, you need to look at the first slow data type of the block and if it is for a header, all of the remaining slow data of the block must be replaced with the new slow data header, even if the slow data type on the subsequent frames is incorrect (corrupted).
I hope you can follow what I am saying, it would be much easier to explain on a piece of paper with a pencil!
Jonathan  G4KLX

**Comment by F4FXL** [comment]
Hi Jonathan,
 
I am still new to all this, and deducted a lot out of the code and the various docs that is scattered all over the web. Anyway I think I understood what you meant.

For you to understand how I came to this code I will just list up what I knew when I wrote it.
1a - The sync pattern always marks the start of the slow data. Sync pattern is always in Frame 0
1b - The slow data is transmitted using 3 bytes chunks, the 3 bytes chunks in odd number frames holds the data type and data length. The exception is free text which is always 20 bytes.
1c - The different types of slow data is interleaved within one block. My first slow data code (which I never committed to the repo) did not handle this and all of the slow data was being stripped because of this.

What I did not know and learned from your previous email
2a - Other types of slow data (GPS, free text) might run over several blocks
2b - The header exists in one block i.e. if I come across a sync pattern while writing the header there is something wrong

Somehow 2b conflicts with 1c, because of interleaving it might happen that the header still spans over several blocks I think ... Yet this depends on the interleaving scheme used ...

73
Geoffrey F4FXL

**Comment by F4FXL** [comment]
Manually merged/committed

**Pull request closed without merging**
